[project]
name = "proyect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "active>=0.0.5a0",
    "black>=25.11.0",
    "click>=8.3.0",
    "numpy>=2.3.4",
    "pylink>=0.3.3",
    "pylint>=4.0.2",
    "pytest>=9.0.0",
    "pytest-cov>=7.0.0",
]
