name: CI

on:
  push:
    branches: [ "Lab1" ]
  pull_request:
    branches: [ "Lab1" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install packages
        run: make install

      - name: Format
        run: make format

      - name: Lint
        run: make lint

      - name: Run tests
        run: make test
